# Generated by Django 4.1.4 on 2022-12-12 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('mobile_operator_code', models.CharField(max_length=3)),
                ('tag', models.CharField(max_length=30)),
                ('time_zone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_id', models.CharField(max_length=30, unique=True)),
                ('started_at', models.DateTimeField()),
                ('message_text', models.TextField()),
                ('mailing_filter', models.CharField(max_length=30)),
                ('ended_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=30, unique=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('sent', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='service.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='service.mailing')),
            ],
        ),
    ]
